def test_closure(func, closure, exc):
    try:
        new.function(func.func_code, {}, '', None, closure)
    except exc:
        pass
    else:
        print 'corrupt closure accepted'
