def test_try_except_finally_no_exception(self):
    hit_except = False
    hit_finally = False
    try:
        try:
            pass
        except:
            hit_except = True
    finally:
        hit_finally = True
    self.assertFalse(hit_except)
    self.assertTrue(hit_finally)
