def test_callbacks_protected(self):


    class BogusError(Exception):
        pass
    data = {}

    def remove(k):
        del data[k]

    def encapsulate():
        f = (lambda : ())
        data[weakref.ref(f, remove)] = None
        raise BogusError
    try:
        encapsulate()
    except BogusError:
        pass
    else:
        self.fail('exception not properly restored')
    try:
        encapsulate()
    except BogusError:
        pass
    else:
        self.fail('exception not properly restored')
