def test_try_except_else(self):
    hit_except = False
    hit_else = False
    try:
        raise Exception, 'foo!'
    except:
        hit_except = True
    else:
        hit_else = True
    self.assertFalse(hit_else)
    self.assertTrue(hit_except)
