def test_invalid_args(self):
    self.assertRaises(TypeError, symtable.symtable, '42')
    self.assertRaises(ValueError, symtable.symtable, '42', '?', '')
