def test_out_of_bounds(self):
    try:
        'a'[10:]
    except StringOutOfBoundsError:
        self.fail('str slice threw StringOutOfBoundsError')
